project_id = "gdscyyzovfyhcwixtoft"

[functions.evolution-webhook]
verify_jwt = false

[functions.kiwify-webhook]
verify_jwt = false

[functions.run-scheduler]
verify_jwt = false

[functions.evolution-connect]
verify_jwt = false